on:
  release:
    types: [published]

jobs:
  release_notes_job:
    runs-on: ubuntu-latest
    name: Release Notes Forwarder
    steps:
    - name: Forward to MS Teams
      id: sending
      uses: colespencer1453/release-notes-action-python@master
      with:
        releasePayload: ${{ toJson(github.event) }}
        teamsWebhook: ${{ secrets.TEAMS_WEB_HOOK }}
          
